### ISSUE TITLE
Adding possibility to create new activities (and retiring old ones)?

### ISSUE THREAD

**Issue by FifthRooter** [emilsbee/rainbow-tracker#18]
Right now it's not possible to create a new activity, and the standard approach to "creating" a new one is to just rename a rarely used one and start using it as new.

The problem with this approach is that there's no distinguishing between projects/jobs/etc, as one keeps renaming the activity to different things. And after a few years it would be impossible to trace back a specific time period during which an activity was used for "Project A", and then afterwards for "Project B" etc.

Looking at an overview over the years, it would be cool to see when and for how long I was working on "Project A", then stopped and started "Project B", and see how my productivity and existence patterns changed as a result of changing projects/jobs.

In addition, in the Settings page under activity settings, you could display a list of "Active activities" and then have a button of "Archived activities" to show those as well? Not sure whether that would be needed, but just brainstorming here.

I know you've thought about this, but was just curious whether it's possible to implement in the current code, and whether there's a plan down the road to implement this. (For me it's getting quite pressing as I'm starting new projects and a new job :D)

**Comment by emilsbee** [comment]
The functionality to add more activities (as well as categories) should be implemented soon because it definitely is crucial. As well as viewing archived categories/activities.

Given that you can create new categories/activities,  you could create a category _work_ and under that, create activities as projects/jobs, then you would be able to view your work on each project over time. However, currently, you have a category _musts_ and under that an activity _work_. This doesn't necessarily allow for what I described before though. Theoretically, I could implement something like tags which you could add and remove from activities. So let's say you add a tag _blacksmith_ to your current _work_ activity, then all activities logged with that tag activated will be saved with that tag. It would likely be possible to view that over time too. However, this might prove to be too much nesting _category_ <- _activity_ <- _tag_. What do you think?

What I personally do is create a new category for each work that I do. And then I add specific activities for the work. Let's say that the category is _software developer at some company_, then I could have activities like _meetings_, _project 1_, _project 2_, _learning_, etc. This works for me, but again you already have a lot of data logged using an activity _work_ under _musts_ category. Hence, besides refactoring your data manually the other option is tags.

**Comment by FifthRooter** [comment]
I think we had a bit of a misunderstanding about how we each categorize the activities - we do it the same way. I have a category "work", and then in that category I have several "activities". I've kept my category count to the original number, and haven't implemented as granular an overview of individual projects, only have an activity per certain work project. 

For me, I'm not sure I want to add more categories than the 4 I currently have (maybe max 5) because I want to maintain the original goal of this app of tracking your life, which, roughly, can be split into 4 broad but distinct life categories (work, sleep, leisure and daily have-to's). Once you start bubbling the work activities up to the categories, you start having multiple work-related categories. This results in too much granular data, which might lead to loss of quality of the data. You want to find a sweet spot between dissecting your life into too many parts and too few, and for me at least, 4 broad categories, each with smaller yet still relatively broad activities, is the sweet spot.

Ultimately every user will choose to do it their own way, so we should certainly add the ability to add&remove both categories and activities. But because the app can be confusing for a newbie, a good on-boarding solution would be to create a "Best Practices" description, where we make a suggestion about how one's life could best be tracked to ensure an optimal balance of level of data granularity and sustainability of daily tracking (keeping tracking consistency high). Something to add to the backlog!

**Comment by emilsbee** [comment]
Properly implement in commit https://github.com/emilsbee/rainbow-tracker/commit/db3fa680f15802f0fc40eba29f3ac547a0594f36
